/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface CustomerOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'customerAddress' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
  'customerEmail' : string,
  'paymentProofUrl' : string,
}
export interface NewCustomerOrder {
  'customerName' : string,
  'customerPhone' : string,
  'customerAddress' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
  'customerEmail' : string,
  'paymentProofUrl' : string,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'items' : Array<CartItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCustomerOrder' : ActorMethod<[NewCustomerOrder], undefined>,
  'seedProducts' : ActorMethod<[], undefined>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];